import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Link from 'next/link'
import {getPageSession} from '@/auth/lucia'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Lucia Azure AD Auth Example',
    description: 'Generated by create next app',
}

export default async function RootLayout({children,}: { children: React.ReactNode }) {
    const session = await getPageSession()

    return (
        <html lang="en">
        <body className={inter.className}>
        <nav className="p-4">
            <ul className="flex w-full justify-center items-center gap-4">
                <li><Link href="/">Home</Link></li>
                {!session ? <li><Link href="login">Login</Link></li>
                    : <li><Link href="logout">Logout</Link></li>}
                <li><Link href="protected">Protected</Link></li>
            </ul>
        </nav>
        <main className="flex flex-col justify-center items-center">
            {children}
        </main>
        </body>
        </html>
    )
}
